#!/usr/bin/env bash

#case "$1" in
#    '???')
#        source dk-h-all
#        exit 0
#        ;;
#    '??')
#        source dk-h-cat
#        exit 0
#        ;;
#    '?')
#        exit 1
#        ;;
#esac



DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2> /dev/null && pwd 2> /dev/null )"


CMD1="${DIR}/dk-${1}"
CMD2="${DIR}/dk-${1}-${2}"

shift

if [ -f ${CMD2} ]
then
    shift
    source ${CMD2} "$@" || exit 1
elif [ -f ${CMD1} ]; then
    source ${CMD1} "$@" || exit 1
else
    ls -1 "${DIR}"/dk-* | xargs basename | sed 's/-/ /g' || exit 1
fi

