#!/usr/bin/env bash


if [ $# -lt 1 ]
then
cat << HELP

dk-repo-tags  --  list all tags for a Docker image on a remote registry.

EXAMPLE:
    - list all tags for ubuntu:
       dk-repo-tags ubuntu

    - list all php tags containing apache:
       dk-repo-tags php apache

HELP
fi

image="$1"
tags=`wget -q https://registry.hub.docker.com/v1/repositories/${image}/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}'`

if [ -n "$2" ]
then
    tags=` echo "${tags}" | grep "$2" | gsort -uV`
fi

echo "${tags}"
